name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Init Repo
      run: git submodule update --init --recursive
    - name: Build Image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
